# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fibonacci.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fibonacci.proto',
  package='fibonacci',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66ibonacci.proto\x12\tfibonacci\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\x32\xe6\x01\n\tFibonacci\x12/\n\x07\x41tIndex\x12\x11.fibonacci.Number\x1a\x11.fibonacci.Number\x12\x35\n\x0bGetSequence\x12\x11.fibonacci.Number\x1a\x11.fibonacci.Number0\x01\x12\x35\n\x0bSumIndicies\x12\x11.fibonacci.Number\x1a\x11.fibonacci.Number(\x01\x12:\n\x0eStreamSequence\x12\x11.fibonacci.Number\x1a\x11.fibonacci.Number(\x01\x30\x01\x62\x06proto3'
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='fibonacci.Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='fibonacci.Number.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'fibonacci_pb2'
  # @@protoc_insertion_point(class_scope:fibonacci.Number)
  })
_sym_db.RegisterMessage(Number)



_FIBONACCI = _descriptor.ServiceDescriptor(
  name='Fibonacci',
  full_name='fibonacci.Fibonacci',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=56,
  serialized_end=286,
  methods=[
  _descriptor.MethodDescriptor(
    name='AtIndex',
    full_name='fibonacci.Fibonacci.AtIndex',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSequence',
    full_name='fibonacci.Fibonacci.GetSequence',
    index=1,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SumIndicies',
    full_name='fibonacci.Fibonacci.SumIndicies',
    index=2,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamSequence',
    full_name='fibonacci.Fibonacci.StreamSequence',
    index=3,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FIBONACCI)

DESCRIPTOR.services_by_name['Fibonacci'] = _FIBONACCI

# @@protoc_insertion_point(module_scope)
